### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ma-sensei-web** [ma-sensei-web/furima-35541#9]
# URL
https://furima-35541.herokuapp.com/

# Basic認証のIDとパスワード
BASIC_AUTH_PASSWORD:      111111
BASIC_AUTH_USER:         　　 maakim

#出品者用のメールアドレスとパスワード
アドレス：　　maakim@com
パスワード：　111qqq

#購入者用のメールアドレスとパスワード
アドレス：　　kim@com
パスワード：　111qqq

**Comment by snkw-works** [comment]
@ma-sensei-web さん、お待たせいたしました。ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/119284553-f48f5c00-bc7a-11eb-887c-2c7e192074b9.png)
